# Clasificador OpenAI gpt-5-mini
Clasifica el dataset de preguntas de red usando la API de OpenAI.

In [37]:
pip install openai pandas tqdm

Requirement already satisfied: openai in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (2.29.0)
Requirement already satisfied: pandas in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (3.0.1)
Requirement already satisfied: tqdm in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (4.67.3)
Requirement already satisfied: anyio<5,>=3.5.0 in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (from openai) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (from openai) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (from openai) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (from openai) (0.13.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (from openai) (2.6.0)
Requirement already satisfied: sniffio in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (from openai) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (from openai) (4.15.0)
Requirement already satisfied: idna>=2.8 in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (from anyio<5,>=3.5.0->openai) (3.11)
Requirement already satisfied: certifi in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (from httpx<1,>=0.23.0->openai) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (from httpx<1,>=0.23.0->openai) (1.0.9)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai) (0.16.0)
Requirement already satisfied: annotated-types>=0.4.0 in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.16.1 in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai) (2.16.1)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/agent/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## Configuración

In [46]:
import os
import re
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(Path("../").resolve() / ".env")

API_KEY = os.getenv("OPENAI_API_KEY")
MODEL = "gpt-5-mini"
INPUT_CSV = "requirements_questions_v2.csv"
OUTPUT_CSV = "requirements_classified_gpt5.csv"
SAMPLE = None  # usa un int para prueba rápida

print(f"API_KEY cargada: {'OK' if API_KEY else 'NO ENCONTRADA'}")
print(f"Modelo: {MODEL}")

API_KEY cargada: OK
Modelo: gpt-5-mini

## Setup

In [ ]:
import json
import pandas as pd
from tqdm.notebook import tqdm
from openai import OpenAI

client = OpenAI(api_key=API_KEY)

CAT_LIST = ["ROUTING", "SECURITY", "QOS", "CONNECTIVITY", "MONITORING", "GENERAL"]
DEBUG_EACH_QUESTION = True
REASONING_EFFORT = "low"

SYSTEM_PROMPT = """You are a Cisco network expert and dataset annotator.
Classify each question into exactly one category from this taxonomy:

ROUTING, SECURITY, QOS, CONNECTIVITY, MONITORING, GENERAL

Taxonomy (brief):
- ROUTING: route calculation/selection and control-plane routing protocols (OSPF, BGP, EIGRP, redistribution, route-maps for routing policy).
- SECURITY: access control and protection mechanisms (ACLs, firewall, VPN/IPsec, AAA, authentication/authorization, segmentation for security intent).
- QOS: traffic classification, marking, policing, shaping, queuing, congestion management/avoidance, and service policies.
- CONNECTIVITY: interface/link bring-up, Layer 2/Layer 3 reachability, addressing, VLAN/trunks, tunnels/overlay setup, adjacency/neighbor establishment issues.
- MONITORING: telemetry, observability, health/performance measurement, logs, SNMP, NetFlow/IPFIX, IP SLA, troubleshooting visibility commands.
- GENERAL: conceptual/vendor-agnostic networking questions that do not fit the above technical domains.

Decision rules:
- Choose the SINGLE most relevant category based on primary intent.
- If multiple domains appear, label by what the user is mainly asking to configure/fix/verify.
- Use GENERAL only as a last resort.
- Respond with a JSON block only. No extra text.

Response format:
```json
{\"category\": \"CATEGORY_NAME\"}
```"""

print("Setup OK")

Setup OK

## Funciones

In [41]:
def parse_json_from_response(text: str) -> dict | None:
    match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(1))
        except json.JSONDecodeError:
            pass
    match = re.search(r"\{[^{}]*\"category\"[^{}]*\}", text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group(0))
        except json.JSONDecodeError:
            pass
    return None


def debug_output(question: str, raw: str, pred: str):
    if not DEBUG_EACH_QUESTION:
        return
    print(
        f"[QUESTION]\n{question}\n[RAW]\n{raw if raw else '<VACÍO>'}\n[PRED]\n{pred}\n"
    )


def classify(question: str) -> str:
    try:
        response = client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user",   "content": question},
            ],
            max_completion_tokens=512,
            reasoning_effort=REASONING_EFFORT,
        )
        raw = (response.choices[0].message.content or "").strip()

        parsed = parse_json_from_response(raw)
        if parsed and parsed.get("category") in CAT_LIST:
            pred = parsed["category"]
            debug_output(question, raw, pred)
            return pred

        for cat in CAT_LIST:
            if cat in raw.upper():
                debug_output(question, raw, cat)
                return cat

        debug_output(question, raw, "UNKNOWN")
        return "UNKNOWN"
    except Exception as e:
        print(f"\n[UNKNOWN] QUESTION:\n{question}\n[ERROR]: {e}\n")
        return "UNKNOWN"

print("Funciones OK")

Funciones OK

## Cargar dataset

In [43]:
df = pd.read_csv(INPUT_CSV)
if "id" not in df.columns:
    df.insert(0, "id", range(len(df)))

if SAMPLE:
    df = df.sample(n=SAMPLE, random_state=42).reset_index(drop=True)
    print(f"Modo prueba: {SAMPLE} registros")

print(f"Total: {len(df)} preguntas")
df[["id", "question"]].head()

Total: 4570 preguntas

   id                                           question
0   0  How can we monitor and store download time wit...
1   1  How can we ensure a network with broader reach...
2   2  How can you ensure that IP SLAs measurements a...
3   3  How do I configure the IP Service Level Agreem...
4   4  How do I enable the IP SLAs Responder on my Ci...

## Clasificar

In [44]:
results: dict[int, str] = {}

all_ids = [int(x) for x in df["id"].tolist()]
print(f"Registros a clasificar: {len(all_ids)}")

for count, row_id in enumerate(tqdm(all_ids, total=len(all_ids)), start=1):
    row = df[df["id"] == row_id].iloc[0]
    question = str(row["question"])

    if DEBUG_EACH_QUESTION:
        print(f"\n--- [{count}/{len(all_ids)}] id={row_id} ---")

    results[row_id] = classify(question)

print("Clasificación completa")

Registros a clasificar: 4570

  0%|          | 0/4570 [00:00<?, ?it/s]

--- [1/4570] id=0 ---
[QUESTION]
How can we monitor and store download time within the Cisco device and configure IP and application layer options for optimal performance?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [2/4570] id=1 ---
[QUESTION]
How can we ensure a network with broader reach and accurate representation of end-user experience while maintaining ease of deployment?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [3/4570] id=2 ---
[QUESTION]
How can you ensure that IP SLAs measurements are continuous, reliable, and predictable?
[RAW]
{"category":"MONITORING"}
[PRED]
MONITORING


--- [4/4570] id=3 ---
[QUESTION]
How do I configure the IP Service Level Agreement (SLA) feature on an ASR 920 platform to measure network performance?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [5/4570] id=4 ---
[QUESTION]
How do I enable the IP SLAs Responder on my Cisco device?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [6/4570] id=5 ---
[QUESTION]
How can I configure an IP SLAs Responder to listen on a specific port for control protocol messages sent by an IP SLAs operation?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [7/4570] id=6 ---
[QUESTION]
What is the recommended configuration to minimize processing delays for accurate response times when using IP SLAs test packets and time stamping?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [8/4570] id=7 ---
[QUESTION]
How can we improve the accuracy of network activity tests in our Cisco device?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [9/4570] id=8 ---
[QUESTION]
How can we configure the Cisco router to send SNMP traps when the round-trip time (RTT) threshold is exceeded?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [10/4570] id=9 ---
[QUESTION]
Can we configure IP SLAs to maintain two hours of aggregated statistics for each operation and also allow the Enhanced History feature with a shorter aggregation interval than an hour?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [11/4570] id=10 ---
[QUESTION]
How can I configure IP SLAs to maintain a snapshot of data for each operation instance that matches a specific filter?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [12/4570] id=11 ---
[QUESTION]
What is the recommended speech codec for Complexity 8 kbit/s CS-ACELP transmission in accordance with ITU-T G.729A standard?
[RAW]
{"category": "QOS"}
[PRED]
QOS


--- [13/4570] id=12 ---
[QUESTION]
What is the purpose of configuring IP SLAs UDP Jitter Operations in a network that carries UDP traffic?
[RAW]
{"category":"MONITORING"}
[PRED]
MONITORING


--- [14/4570] id=13 ---
[QUESTION]
What happens to one-way delay measurements when time synchronization is not required for one-way jitter and packet loss measurements in Cisco IOS?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [15/4570] id=14 ---
[QUESTION]
How can we measure positive and negative jitter values for delay-sensitive networks like VoIP, with an ideal jitter value of 0 ms?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [16/4570] id=15 ---
[QUESTION]
How can we configure asymmetric UDP jitter operation to monitor round-trip delay in a network with customizable packet sizes per direction?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [17/4570] id=16 ---
[QUESTION]
What are the UDP Jitter Operation Parameters configured to simulate IP service?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [18/4570] id=17 ---
[QUESTION]
How do you enable IP SLAs responder functionality on a Cisco device?
[RAW]
{"category":"MONITORING"}
[PRED]
MONITORING


--- [19/4570] id=18 ---
[QUESTION]
How do you configure a basic UDP jitter operation on a source device?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [20/4570] id=19 ---
[QUESTION]
What is the frequency at which the IP SLA operation will run in seconds?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [21/4570] id=20 ---
[QUESTION]
How to enable and configure IP SLAs Responder on the target device for UDP jitter operation?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [22/4570] id=21 ---
[QUESTION]
How many hours of statistics are maintained for an IP SLA jitter operation when the frequency is set to 30?
[RAW]
{"category":"MONITORING"}
[PRED]
MONITORING


--- [23/4570] id=22 ---
[QUESTION]
How can we configure IP SLAs to monitor network statistics for TelnetPollServer1 with a threshold value of 10 seconds?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [24/4570] id=23 ---
[QUESTION]
How can I configure the percentile option for IP SLAs operations?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [25/4570] id=24 ---
[QUESTION]
How can you configure the scheduling parameters for an individual IP SLAs operation to run indefinitely?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [26/4570] id=25 ---
[QUESTION]
What is the schedule period for IP SLAs group schedule 10?
[RAW]
{"category":"MONITORING"}
[PRED]
MONITORING


--- [27/4570] id=26 ---
[QUESTION]
How can we configure proactive threshold conditions to trigger traps when an IP Service Level Agreement (SLA) operation exceeds the defined threshold?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [28/4570] id=27 ---
[QUESTION]
How do we configure the UDP Jitter test in IP SLAs to monitor performance from host 192.0.2.115 at port 65052 with 20 packets sent every 10 seconds?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [29/4570] id=28 ---
[QUESTION]
What is the purpose of the "ip sla responder" command in Cisco IOS?
[RAW]
{"category":"MONITORING"}
[PRED]
MONITORING


--- [30/4570] id=29 ---
[QUESTION]
What is the expected output of UDP jitter operation with one-way delay measurements in our network configuration?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [31/4570] id=30 ---
[QUESTION]
How do you configure IP SLAs Responder on a destination device without configuring a permanent port for a sender?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [32/4570] id=31 ---
[QUESTION]
How can I enable IP SLAs responder functionality on a specific port and VRF?
[RAW]
{"category":"MONITORING"}
[PRED]
MONITORING


--- [33/4570] id=32 ---
[QUESTION]
How can you exit global configuration mode and return to privileged EXEC mode?
[RAW]
{"category": "GENERAL"}
[PRED]
GENERAL


--- [34/4570] id=33 ---
[QUESTION]
How can I add multicast responder IP addresses to the endpoint list in Cisco IOS?
[RAW]
{"category":"ROUTING"}
[PRED]
ROUTING


--- [35/4570] id=34 ---
[QUESTION]
What is the maximum number of hours that UDP jitter operations with history buckets can keep statistics for in Cisco routers?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [36/4570] id=35 ---
[QUESTION]
How to configure IP SLAs Multicast Support for UDP Jitter operations?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [37/4570] id=36 ---
[QUESTION]
How do you configure UDP Jitter operations for a multicast endpoint using IP SLAs on Cisco IOS XE Gibraltar?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [38/4570] id=37 ---
[QUESTION]
What are the default settings for retry attempts and timeout seconds when configuring control commands on a Cisco router?
[RAW]
{"category": "GENERAL"}
[PRED]
GENERAL


--- [39/4570] id=38 ---
[QUESTION]
How do you configure IP SLA operations for multicast jitter measurements?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [40/4570] id=39 ---
[QUESTION]
How do you configure the scheduling parameters for an individual IP SLAs operation?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [41/4570] id=40 ---
[QUESTION]
How can I enable data verification for IP SLA operations and troubleshoot issues with an IP SLAs operation?
[RAW]
{"category":"MONITORING"}
[PRED]
MONITORING


--- [42/4570] id=41 ---
[QUESTION]
How can we configure IP SLA to measure one-way latency, jitter, and packet loss for each multicast receiver in a user-specified multicast group?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [43/4570] id=42 ---
[QUESTION]
How do you configure an IP Service Level Agreements (SLAs) User Datagram Protocol (UDP) jitter operation to proactively monitor Voice over IP (VoIP) quality levels in your network?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [44/4570] id=43 ---
[QUESTION]
How can we configure IP SLAs to measure UDP jitter operations for VoIP without supporting RTP?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [45/4570] id=44 ---
[QUESTION]
What is the typical method used to evaluate the performance of UDP-based VoIP traffic when configuring IP SLAs operations?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [46/4570] id=45 ---
[QUESTION]
What are the default operation parameters for VoIP UDP jitter measurement using different codecs (g711 mu-Law, g711 A-Law, G.729A) in Cisco IOS?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [47/4570] id=46 ---
[QUESTION]
What is the default Advantage Factor for IP SLAs VoIP UDP jitter operations?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [48/4570] id=47 ---
[QUESTION]
How can we configure IP SLAs UDP Jitter Operations for VoIP without assigning a permanent port to the sender?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [49/4570] id=48 ---
[QUESTION]
How do you configure the IP SLAs responder functionality on a Cisco device?
[RAW]
{"category":"MONITORING"}
[PRED]
MONITORING


--- [50/4570] id=49 ---
[QUESTION]
How do you configure the IP SLAs Responder on a destination device?
[RAW]
{"category":"MONITORING"}
[PRED]
MONITORING


--- [51/4570] id=50 ---
[QUESTION]
How can we configure and schedule an IP SLAs VoIP UDP Jitter operation using G.711 A Law compression method?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [52/4570] id=51 ---
[QUESTION]
What is the statistic distribution interval in milliseconds for UDP jitter measurement?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [53/4570] id=52 ---
[QUESTION]
What command can you use to enable enhanced history gathering for an IP SLAs operation?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [54/4570] id=53 ---
[QUESTION]
What is the configuration to set the SNMP owner for an IP SLAs operation?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [55/4570] id=54 ---
[QUESTION]
How do I schedule IP SLAs operations with default configuration values or specify a specific operation?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [56/4570] id=55 ---
[QUESTION]
How do you configure IP SLAs UDP Jitter monitoring to measure VoIP quality, targeting an address of 209.165.200.225 with a specific codec and advantage factor?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [57/4570] id=56 ---
[QUESTION]
What is the operation frequency for Jitter Operation with Codec Type g711alaw?
[RAW]
{"category": "QOS"}
[PRED]
QOS


--- [58/4570] id=57 ---
[QUESTION]
How do I configure IP Service Level Agreement (SLA) UDP Jitter operations for VoIP in Cisco IOS?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [59/4570] id=58 ---
[QUESTION]
How can we measure jitter, packet loss, delay, and round-trip time in a network?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [60/4570] id=59 ---
[QUESTION]
How can I simulate UDP traffic with customizable packet sizes, interval, and frequency in Cisco IOS?
[RAW]
{"category":"MONITORING"}
[PRED]
MONITORING


--- [61/4570] id=60 ---
[QUESTION]
How can we measure UDP jitter using IP SLAs operations to capture metrics like round-trip time, one-way delay, jitter, and packet loss?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [62/4570] id=61 ---
[QUESTION]
What is the recommended method to achieve time synchronization between source and target devices for accurate one-way delay measurements?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [63/4570] id=62 ---
[QUESTION]
How do you configure the IP SLAs Responder on the destination device without a permanent port for the same sender?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [64/4570] id=63 ---
[QUESTION]
How can we configure a UDP jitter probe with QFP time stamping on the source device?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [65/4570] id=64 ---
[QUESTION]
To enable privileged EXEC mode and configure an IP SLAs operation for UDP jitter, what is the correct Cisco IOS command sequence to use?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [66/4570] id=65 ---
[QUESTION]
What are the default and optional configuration values for an IP SLAs operation with operation number 10?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [67/4570] id=66 ---
[QUESTION]
How can I configure the UPD Jitter Operation with QFP Time Stamping on my XE Gibraltar 16.11.x router?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [68/4570] id=67 ---
[QUESTION]
How can we configure enhanced history gathering for IP SLA operation with specified interval, buckets, frequency, and hours of statistics kept?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [69/4570] id=68 ---
[QUESTION]
What is the time interval set for each statistics distribution kept for an IP SLAs operation?
[RAW]
{"category":"MONITORING"}
[PRED]
MONITORING


--- [70/4570] id=69 ---
[QUESTION]
How can we set the timeout for an IP SLAs operation in milliseconds?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [71/4570] id=70 ---
[QUESTION]
What is the requirement for adding operations to a multioperation group in Cisco IOS?
[RAW]
{"category": "GENERAL"}
[PRED]
GENERAL


--- [72/4570] id=71 ---
[QUESTION]
How can I configure a UDP operation with QFP time stamping and optimized timestamp location?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [73/4570] id=72 ---
[QUESTION]
How do I use Cisco MIB Locator to download MIBs for selected platforms, Cisco IOS releases, and feature sets?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [74/4570] id=73 ---
[QUESTION]
How can we enable IP SLAs Cisco Packet Processor (CPP) time stamping to improve the accuracy of IP SLAs UDP jitter operations on our Cisco ASR 1000 Series routers?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [75/4570] id=74 ---
[QUESTION]
What is required to configure an IP Service Level Agreements (SLAs) label switched path (LSP) Health Monitor in order to proactively monitor Layer 3 Multiprotocol Label Switching (MPLS) Virtual Private Networks (VPNs)?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [76/4570] id=75 ---
[QUESTION]
What is the recommended configuration for an LSP Health Monitor operation to function effectively?
[RAW]
{"category":"MONITORING"}
[PRED]
MONITORING


--- [77/4570] id=76 ---
[QUESTION]
What is the minimum memory requirement for the LSP Health Monitor functionality to operate correctly?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [78/4570] id=77 ---
[QUESTION]
What are the restrictions for configuring IP SLAs LSP Health Monitor operations?
[RAW]
{"category":"MONITORING"}
[PRED]
MONITORING


--- [79/4570] id=78 ---
[QUESTION]
What is the syntax to configure the start time and frequency for each measurement in the LSP Health Monitor operation?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [80/4570] id=79 ---
[QUESTION]
How can we filter BGP next hop neighbors discovered by the LSP Health Monitor using standard IP access lists?
[RAW]
{"category": "ROUTING"}
[PRED]
ROUTING


--- [81/4570] id=80 ---
[QUESTION]
How can I discover the BGP next-hop neighbors in use by any VRF associated with the source PE device?
[RAW]
{"category":"ROUTING"}
[PRED]
ROUTING


--- [82/4570] id=81 ---
[QUESTION]
How does the IP SLAs superoperation measure network connectivity across all equal-cost multipaths between the source PE device and discovered destination PE device?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [83/4570] id=82 ---
[QUESTION]
How can we assign unique identification numbers starting with the number 1 for MPLS VPN core network for BGP next hop neighbor assignment?
[RAW]
{"category": "ROUTING"}
[PRED]
ROUTING


--- [84/4570] id=83 ---
[QUESTION]
How can we store results as group averages representative of equal-cost multipaths within the LSP discovery group for a given one-hour increment?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [85/4570] id=84 ---
[QUESTION]
What is the recommended method to monitor network connectivity between the source PE device and destination PE devices?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [86/4570] id=85 ---
[QUESTION]
What is required to enable proactive threshold monitoring for LSP Health Monitor operations?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [87/4570] id=86 ---
[QUESTION]
What is the purpose of monitoring LSP Health using primary and secondary frequencies when testing the status of paths belonging to a group?
[RAW]
{"category":"MONITORING"}
[PRED]
MONITORING


--- [88/4570] id=87 ---
[QUESTION]
How can you configure the LSP Health Monitor feature to automatically schedule IP SLAs operations with evenly distributed intervals over a specified duration?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [89/4570] id=88 ---
[QUESTION]
How do you enable MPLS discovery VPN Next-Hop using the auto ip sla mpls-lsp-monitor command?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [90/4570] id=89 ---
[QUESTION]
What is the correct value for the "experimental" field in the header of an echo request packet used in IP SLAs operations?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [91/4570] id=90 ---
[QUESTION]
What is the secondary frequency setting for IP Service Level Agreement (SLA) operation in case of a connection loss?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [92/4570] id=91 ---
[QUESTION]
What is the purpose of the `mpls discovery vpn next-hop` command in Cisco IOS?
[RAW]
{"category": "ROUTING"}
[PRED]
ROUTING


--- [93/4570] id=92 ---
[QUESTION]
How can you configure an LSP Health Monitor operation using auto IP SLAs MPLS configuration mode?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [94/4570] id=93 ---
[QUESTION]
What is the default value for `hours-of-statistics-kept` in LSP Health Monitor operation configuration?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [95/4570] id=94 ---
[QUESTION]
What is the recommended configuration to limit the number of BGP next hop neighbors undergoing LSP discovery for a single LSP Health Monitor operation?
[RAW]
{"category": "ROUTING"}
[PRED]
ROUTING


--- [96/4570] id=95 ---
[QUESTION]
How can I enable SNMP system logging messages specific to IP SLAs trap notifications?
[RAW]
{"category":"MONITORING"}
[PRED]
MONITORING


--- [97/4570] id=96 ---
[QUESTION]
How do you configure an IP SLAs LSP Ping or LSP Traceroute operation in Cisco IOS?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [98/4570] id=97 ---
[QUESTION]
How do you configure an IP SLA operation as an LSP ping operation in Cisco IOS?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [99/4570] id=98 ---
[QUESTION]
What is the command to configure IP SLAs actions based on events and generate SNMP system logging messages for IP SLAs trap notifications?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [100/4570] id=99 ---
[QUESTION]
** How can you display the operational status of the LSP discovery groups belonging to an LSP Health Monitor operation?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [101/4570] id=100 ---
[QUESTION]
How do we configure the LSP Health Monitor to automatically monitor the health of LSPs within the MPLS VPN network?
[RAW]
{"category": "MONITORING"}
[PRED]
MONITORING


--- [102/4570] id=101 ---
[QUESTION]

## Exportar y revisar resultados

In [47]:
df["category"] = [results.get(int(row_id), "UNKNOWN") for row_id in df["id"]]
df.to_csv(OUTPUT_CSV, index=False)
print(f"Dataset guardado: {OUTPUT_CSV}")

unknown_count = int((df["category"] == "UNKNOWN").sum())
print(f"UNKNOWN: {unknown_count}")

print("\n=== DISTRIBUCIÓN FINAL ===")
display(df["category"].value_counts().to_frame())

df[["id", "question", "category"]].head(10)

Dataset guardado: requirements_classified_gpt5.csv
UNKNOWN: 0

=== DISTRIBUCIÓN FINAL ===

              count
category
SECURITY       1269
ROUTING        1161
MONITORING      777
QOS             652
CONNECTIVITY    612
GENERAL          99

   id                                           question    category
0   0  How can we monitor and store download time wit...  MONITORING
1   1  How can we ensure a network with broader reach...  MONITORING
2   2  How can you ensure that IP SLAs measurements a...  MONITORING
3   3  How do I configure the IP Service Level Agreem...  MONITORING
4   4  How do I enable the IP SLAs Responder on my Ci...  MONITORING
5   5  How can I configure an IP SLAs Responder to li...  MONITORING
6   6  What is the recommended configuration to minim...  MONITORING
7   7  How can we improve the accuracy of network act...  MONITORING
8   8  How can we configure the Cisco router to send ...  MONITORING
9   9  Can we configure IP SLAs to maintain two hours...  MONITORING